sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot

before-deploy:
  - git config --local user.name tewmansi
  - git config --local user.email mansi.tewari@gmail.com
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
      
deploy:
  provider: releases
  skip-cleanup: true
  api-key: '$GITHUB_API_KEY'
  keep-history: true
  file_glob: true
  file: dist/**/*  
